### ISSUE TITLE
How to deploy vmware-vms in specially resources pool ?

### ISSUE THREAD

**Issue by hegphegp** [cloudmaniac/ansible-deploy-vmware-vm#2]
* which param could I config to deploy vmware-vms in specially resources pool

![image](https://user-images.githubusercontent.com/26202719/66926750-2254fd80-f061-11e9-9b18-7d5d73a5bdc7.png)

**Comment by cloudmaniac** [comment]
That's a good suggestion. I don't have time to add it right now, but you can add the following parameters in the main.yml of the roles: "resource_pool". Then add a new variable in the variable file.

**Comment by cloudmaniac** [comment]
I don't know if you still need it, but I added resource pools support. It's disabled by default as it's commented in the role but README contains a note that explains how to use it.

I used this method as I didn't want to create something too complex.
