### ISSUE TITLE
Inventory file (vms-to-deploy) not picking these parameters  "guest_hostname, guest_vcpu, guest_vram, guest_custom_ip"

### ISSUE THREAD

**Issue by avi1512** [cloudmaniac/ansible-deploy-vmware-vm#5]
Hello Mates,

  Inventory file is not picking these parameters  "guest_hostname, guest_vcpu, guest_vram, guest_custom_ip"
  when I run the playbook I got below error msg.. variable is not defined for guest_hostname.. 

[root@test ansible-deploy-vmware-vm]# ansible-playbook -i vms-to-deploy deploy-kubernetes-prod.yml -vvv
ansible-playbook 2.9.15
  config file = /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/ansible.cfg
  configured module search path = [u'/opt/myagent/avi/ansible/ansible-deploy-vmware-vm/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/ansible.cfg as config file
host_list declined parsing /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/vms-to-deploy as it did not pass its verify_file() method
script declined parsing /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/vms-to-deploy as it did not pass its verify_file() method
auto declined parsing /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/vms-to-deploy as it did not pass its verify_file() method
Parsed /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/vms-to-deploy inventory source with ini plugin
Read vars_file 'answerfile.yml'

PLAYBOOK: deploy-kubernetes-prod.yml ***************************************************************************************************************************************
1 plays in deploy-kubernetes-prod.yml
Read vars_file 'answerfile.yml'
Read vars_file 'answerfile.yml'
Read vars_file 'answerfile.yml'

PLAY [all] *****************************************************************************************************************************************************************
META: ran handlers
Read vars_file 'answerfile.yml'
Read vars_file 'answerfile.yml'

TASK [deploy-vsphere-template : Deploy VM from template] *******************************************************************************************************************
task path: /opt/myagent/avi/ansible/ansible-deploy-vmware-vm/roles/deploy-vsphere-template/tasks/main.yml:3
Read vars_file 'answerfile.yml'
Read vars_file 'answerfile.yml'
fatal: [guest_hostname=test-deploy1]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'guest_hostname' is undefined\n\nThe error appears to be in '/opt/myagent/avi/ansible/ansible-deploy-vmware-vm/roles/deploy-vsphere-template/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Deplo/ a VM from a template using Ansible 'vmware_guest' module\n- name: Deploy VM from template\n  ^ here\n"
}
fatal: [guest_hostname=test-deploy2]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'guest_hostname' is undefined\n\nThe error appears to be in '/opt/myagent/avi/ansible/ansible-deploy-vmware-vm/roles/deploy-vsphere-template/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Deplo/ a VM from a template using Ansible 'vmware_guest' module\n- name: Deploy VM from template\n  ^ here\n"
}

PLAY RECAP *****************************************************************************************************************************************************************
guest_hostname=test-deploy1 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
guest_hostname=test-deploy2 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

my inventory file like this 
[vms]
guest_hostname='test-deploy1' guest_vcpu='1' guest_vram='2096' guest_custom_ip='0.0.0.0'
guest_hostname='test-deploy2' guest_vcpu='2' guest_vram='4096' guest_custom_ip='0.0.0.0'

I ran playbook like these
ansible-playbook -i (path of inventory file) (playbook path) -vvv

[root@test ansible-deploy-vmware-vm]# tree
.
├── ansible.cfg
├── answerfile.yml
├── deploy-kubernetes-prod.yml
├── README.md
├── roles
│   └── deploy-vsphere-template
│       └── tasks
│           └── main.yml
└── vms-to-deploy

3 directories, 6 files

Kindly help this

 what was I missed here ??..

**Comment by cloudmaniac** [comment]
Hi,
from what I can see this looks like a syntax issue, related to the way you constructed your inventory file.
Ansible is expecting the first item to be the hostname, you can check the [documentation](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) for more info.

Could you try with this below and let me know?
```
test-deploy1 guest_vcpu='1' guest_vram='2096' guest_custom_ip='0.0.0.0'
test-deploy2 guest_vcpu='2' guest_vram='4096' guest_custom_ip='0.0.0.0'
```

**Comment by avi1512** [comment]
Thanks a lot Romain, it's works perfect..
Now I got the inventory file excepting the first item to be a hostname or IP..

I have one more doubt regarding disk related.. When we deploy multiple VM's they need's multiple disk as well as different layout depends upon the app basis for example app servers need two different disk, DB need three.. like that way 

In that situation I declared disk variables as I need in inventory file

it's look like 

APP guest_vcpu='1' guest_vram='2096' guest_custom_ip='0.0.0.0' guest_disk1='100' guest_disk2='200'
DB guest_vcpu='2' guest_vram='4096' guest_custom_ip='0.0.0.0' guest_disk1='100' guest_disk2='200' guest_disk3='300' 

In playbook I modified in disk part like this 

disk:
    - size_gb: '{{ guest_disk1 }}'
      type: thin
      datastore: '{{ datastore }}'
      failed_when: false
      changed_when: false
    - size_gb: '{{ guest_disk2 }}'
      type: thin
      datastore: '{{ datastore }}'
      failed_when: false
      changed_when: false
    - size_gb: '{{ guest_disk3 }}'
      type: thin
      datastore: '{{ datastore }}'
      failed_when: false
     changed_when: false 
     
     Problem I'm facing when I ran the playbook it's deploying DB server only not APP because it's failing with this error
     "**undefined variable. The error was: 'guest_disk3**'" 
     
     So I tired to ignore the fatal error and proceed the tasks further with this modules failed_when: false, changed_when: false
     but still I have no luck to build the APP server.. 
     
     fatal: [APP]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'guest_disk3' is undefined\n\nThe error appears to be in '/opt/myagent/avi/ansible/ansible-deploy-vmware-vm/roles/deploy-vsphere-template/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Deplo/ a VM from a template using Ansible 'vmware_guest' module\n- name: Deploy VM from template\n  ^ here\n"
}
     
     PLAY RECAP *****************************************************************************************************************************************************************
APP               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
DB                 : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

     Is there any way to procced the task without fatal error or we can ignore error any other ways ???
     
     Thanks for Advance

**Comment by cloudmaniac** [comment]
Well, you can have a look at the [error handling documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html), but I don't think it will be OK for you.

Some solutions:

-  a [conditional](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html) that will test if the variable is present and if not, the playbook will not add the disk
- different playbooks with different needs
- play with tags

As those additional configuration have nothing to do with my example, I'll close the issue.

**Comment by avi1512** [comment]
Thanks a lot for your help,

 Yes I checked error handling but it's not supported in vmware_guest module..
